dist: trusty
sudo: required

language: java
jdk: oraclejdk8

branches:
  only:
  - master

addons:
  sonarcloud:
    organization: pociot-github
    token:
      secure: SlWgWMDVgIEICj6ixuhiIjdsNQb3BN6uO0bYrrN/IXRNgf50CNuZJdLGxMSUtoQq/daGoUbI6SQKHRy/LyaVMhc4Lo4ndc2e546vm8tr71QZ5VaU9q9p+tjJNcR+aATxYMbSp5UoBqjDvZtgXFNZAQZRVZ8Hd/vqpkrfFpzCnLQQ+teBbydZD6LpHjV68Ek92yhi97cNGNRWnECWTb4HhZ1qXuaiEiw6H7M1cqqN98s+Kg9ebL0uzz8/odTDNSkjxsP7dz0gSWgpg+gkb5vMOSkLpr8VVC6f4gdy6G5mCPVyNaSBa2Xp8iADCgeZ9g/dHc0NracvtI4SW3Fyp2pW/ZcrjAku8WwjL2xbUtOidREVoyTGSc8ZEJjWpUogOFgeyP+KyvSnC73g70sMTo5sjSzN1tK408p0jlTTfER9ZD1oz7LT82FQEt8OnmbdOQLJwtnudaBccWfsgxbyP7uEymcbDLcqveDKmxyIQZ6KjUjgWFbjLmWC3eCNmLUVaSzewP8u+/lQXo7itwjYDZeYYG5oKnvSYMWafdBy01FUhllEdcogRGXqMqDWE7vovNulHCvzSr4EJuaq/m72kK40yjgMnoV2XT3T1i/mFCQAPfXVzxAYDxsfqtTBHmcCUbyuRyoXCmQPC7Z0i6PRgMP8cX4j0J/Ygr0KJweJNqK7140=

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package
- sonar-scanner

deploy:
  provider: heroku
  api_key:
    secure: VaoiID+wMqzkwhUhm4czRaNIWqApd+OeHt3FLThS+NqyBM8RfztJNZ6VB/cfbD350ho6EnfM6N8rV67jwlrErSaLVhYL3VzlV5nk+A591EITb716YE6Z7bUR4CGIjyloIWoNOtT+y+5ZeY60qp4BFfhbGQ3srMWsDN3Nu69krSN/lvQuqoA6K2gnifxVmoo0RN6V+epv3EXUi6nhF0botYnDj6bEljoNIk1S3wikkenyzhwIGeiqiocA8Cz35dy/WYWoj/pYiPJxwylk1XWoMaj47uVBSESuz160Ktlxj36jkwdVGW2LOIBTfIFLN2Xj08apWNPIePOIN4COalLD0Sy+wCqF/xCZqXTTTLwuz9l4VySDJx+7AI+Jb3X3ZRi0vgqM8+y4tgwk8YMBKYJKMUOyZYt6vpup/RdGaOrzd0fEmwVJKGCqt5XoWaxxkwYuTsX/dCU7Bkivt17wcK+AUpprqfbxSKdCKhaMwCfreLaG6K5FCms932WZFmmQFcjPQfptk8b4qUfXDM3I3ZpRGEqr+0DXqYwXSVnTv0onpx0pH9u/cEcuyr4Q8YJsfccV+QrVCsZDdCvB+6Hfv55tKYfPWyVgFVhcVRphwYO38jatYO+BN7vCppAJemDA8imDkTSHlo/bXpOrie8g0OJXrGMt9Q5QxCkEm38uFsuT8B4=
  app: hcb-account-auth-kpociot
  on:
    repo: pociot/hcb-auth-service
