spring:
  application:
    name: hcb-auth-service

logging.level.org.springframework.security: DEBUG

server:
  port: 8383

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/